### ISSUE TITLE
Feature Request - Footnote display

### ISSUE THREAD

**Issue by adalibas** [andrewshen/sep-plus#1]
First of all, I would like to thank you for your time developing this extension. 
Better appearance, dark mode, and fluff removal when printing are so helpful!

Assuming that you would appreciate some feedback, I would make some suggestions;

1) Can there be a way to improve the readability of footnotes?
For example, it would be awesome if the footnote text were displayed when hovered on the footnote number. 
Automatically, including a footnotes pane could be useful as well.

2) Again on footnotes: would it be possible to include the footnotes to printed text automatically (I am sure it is easy to remove some text from printing than adding some text, but it could be useful.)

One last suggestion;

3) The readme file suggest that the extension also provides keyboard shortcuts for search functions. 
It would be nice if you also include what those shortcuts are.

Thanks again.

**Comment by andrewshen** [comment]
https://github.com/andrewshen/sep-plus/commit/94fdd3e8f6c585e1657eb08238e2c800d8aa65b5
